openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /topic1:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json: {}
  /topic2:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json: {}
  /topic3:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json: {}
  /topic1/sub-topic1:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json: {}
